2011-04-07 03:39:55.691 [WARN] org.opentox.toxotis.database.engine.user.AddUser:72 - SQL statement execution failed while trying to add user in the database
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Sopasakis@opensso.in-silico.ch' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.opentox.toxotis.database.engine.user.AddUser.write(AddUser.java:68)
	at org.opentox.jaqpot3.resources.AlgorithmResource.post(AlgorithmResource.java:145)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:465)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:522)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:258)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:752)
	at org.restlet.resource.Finder.handle(Finder.java:515)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Router.doHandle(Router.java:472)
	at org.restlet.routing.Router.handle(Router.java:688)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:152)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:111)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:72)
	at org.restlet.Application.handle(Application.java:379)
	at org.restlet.ext.wadl.WadlApplication.handle(WadlApplication.java:769)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Router.doHandle(Router.java:472)
	at org.restlet.routing.Router.handle(Router.java:688)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Router.doHandle(Router.java:472)
	at org.restlet.routing.Router.handle(Router.java:688)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:152)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.routing.Filter.doHandle(Filter.java:156)
	at org.restlet.routing.Filter.handle(Filter.java:203)
	at org.restlet.engine.ChainHelper.handle(ChainHelper.java:111)
	at org.restlet.Component.handle(Component.java:385)
	at org.restlet.Server.handle(Server.java:474)
	at org.restlet.engine.ServerHelper.handle(ServerHelper.java:71)
	at org.restlet.engine.http.HttpServerHelper.handle(HttpServerHelper.java:150)
	at org.restlet.ext.grizzly.internal.HttpParserFilter.execute(HttpParserFilter.java:84)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:135)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:102)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:88)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:53)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:57)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:69)
	at com.sun.grizzly.util.FixedThreadPool$BasicWorker.dowork(FixedThreadPool.java:379)
	at com.sun.grizzly.util.FixedThreadPool$BasicWorker.run(FixedThreadPool.java:360)
	at java.lang.Thread.run(Thread.java:662)
2011-04-07 03:39:58.273 [DEBUG] org.opentox.toxotis.database.engine.task.UpdateTask:181 - SQL exception while updating task - rolling back
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'dfb9f13c' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
	at com.mysql.jdbc.Util.getInstance(Util.java:382)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1967)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1449)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeBatch(NewProxyPreparedStatement.java:1723)
	at org.opentox.toxotis.database.engine.task.UpdateTask.update(UpdateTask.java:176)
	at org.opentox.jaqpot3.www.services.RunnableTaskService.updateFailedTask(RunnableTaskService.java:46)
	at org.opentox.jaqpot3.www.services.TrainingService.run(TrainingService.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
2011-04-07 03:39:58.368 [DEBUG] org.opentox.toxotis.database.engine.task.UpdateTask:184 - connection rolled back after failure to update task
